### ISSUE TITLE
Room templates

### ISSUE THREAD

**Issue by ClaudiaMia** [Project-Pandora-Game/pandora#188]
We need a generic way to create and later load a "template" of a room (similar to how BCX offered such a feature for BC).
This issue will depend on #164 , #80 , and #70 .

It is important to do it in such a way, that even very outdated templates or intentionally manipulated ones will be able to be loaded without issues or possible exploits.

This includes saving templates of all room-level (large) items (like furniture) into one template bundle and then a way of loading them all, putting them on the same position inside the room.

Relevant parts:

- [ ] determine the settings that should be stored in the template (likely all an owner can set for a room), including room-level devices and their "configuration state" (likely reusing the item template from #164 )
- [ ] create concept on how to store room data in certain format (likely similar to how item templates are made)
- [ ] consider the maximum limit of allowed room items per room (like set in #80 )

Further issues that need to be created or done as part of this one:

- [ ] decide if we want to allow storing room templates on the server or only offer export/import ||| the issue is dealing with container room devices that could store a potentially unlimited number of items (note: we should set a minimum for the pocket dimension) -> potentially it is fine to include that if all storage items have reasonable maximum numbers and the maximum number of the biggest storage item in one room all filled times 5 rooms per account is nothing that impacts our server 
- [ ] find a way to export the room template as a string (to the clipboard for instance) and also support import (likely similar to #164 )
- [ ] find a suitable way to export too large string optionally as file and also support import (likely similar to #164 )
