### ISSUE TITLE
[META] Mobile improvements

### ISSUE THREAD

**Issue by Jomshir98** [Project-Pandora-Game/pandora#68]
# This issue is for tracking small mobile issues in general
It should be edited or commented on, but not closed.
Game-breaking issues should have separate issue created.
---

- [ ] Top menu should turn into hamburger menu on narrow screens, sliding onto screen only when opened
- [ ] DM menu should hide selection when friend is selected
- [ ] Settings menu has too large min width on fieldsets, causing unnecessary horizontal overflow
- [ ] Settings menu should separate horizontal scrolling of tabs and content
- [ ] Character selection screen is not centered
- [ ] Wardrobe: Cannot scroll when touching canvas even tho it has no interactivity
- [ ] Wardrobe: It is not mobile friendly at all in general
